"""Phase 7 chart generation.

Reads results/ parquet and JSON files, builds matplotlib figures, and saves
PNG images to reports/figures/ at 150 dpi.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import pandas as pd

from data.config import FIGURES_DIR, RESULTS_DIR, ensure_dirs

if TYPE_CHECKING:
    from collections.abc import Sequence

def set_style() -> None:
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.size": 8,
        "figure.dpi": 150,
        "figure.figsize": (7, 4),
        "axes.prop_cycle": plt.cycler("color", plt.cm.tab10.colors),
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.1,
    })


def _read_portfolio_daily(
    universe: str,
    tag: str | None,
    cadence: str,
    lookback: int,
) -> pd.DataFrame | None:
    candidates: list[Path]
    if tag:
        candidates = [
            RESULTS_DIR / "portfolio" / f"daily_returns_{universe}_{tag}_{cadence}_{lookback}d.parquet"
        ]
    else:
        candidates = [
            RESULTS_DIR / "portfolio" / f"daily_returns_{universe}_{cadence}_{lookback}d.parquet",
            # Some portfolio runs append cadence twice (e.g. weekly_weekly);
            # this fallback handles a prior naming inconsistency in portfolio output.
            RESULTS_DIR / "portfolio" / f"daily_returns_{universe}_{cadence}_{cadence}_{lookback}d.parquet",
        ]
    path = next((p for p in candidates if p.exists()), None)
    if path is not None:
        df = pd.read_parquet(path)
        df["date"] = pd.to_datetime(df["date"])
        return df.sort_values("date")

    # Fallback: read ATC decile baseline from quintile output.
    # The decile long-short portfolio is generated by backtest/quintile.py
    # and stored under results/quintile/, not results/portfolio/. If the
    # baseline was not also run through backtest/portfolio.py, use this fallback.
    if tag is None:
        quintile_path = RESULTS_DIR / "quintile" / f"quintile_equity_curves_{universe}.parquet"
        if quintile_path.exists():
            qdf = pd.read_parquet(quintile_path)
            key = f"{lookback}d_Total"
            subset = qdf[qdf["_key"] == key].copy()
            if not subset.empty:
                subset = subset.rename(columns={"long_short": "pnl"})
                subset.index.name = "bucket_date"
                subset = subset.reset_index().rename(columns={"bucket_date": "date"})
                subset["date"] = pd.to_datetime(subset["date"])
                return subset[["date", "pnl"]].sort_values("date").dropna()

    return None


def _read_portfolio_summary(
    universe: str,
    tag: str | None,
    cadence: str,
    lookback: int,
) -> dict | None:
    if tag:
        candidates = [
            RESULTS_DIR / "portfolio" / f"summary_{universe}_{tag}_{cadence}_{lookback}d.json"
        ]
    else:
        candidates = [
            RESULTS_DIR / "portfolio" / f"summary_{universe}_{cadence}_{lookback}d.json",
            RESULTS_DIR / "portfolio" / f"summary_{universe}_{cadence}_{cadence}_{lookback}d.json",
        ]
    path = next((p for p in candidates if p.exists()), None)
    if path is None:
        return None
    with open(path) as f:
        return json.load(f)


def _find_model_tags(
    universe: str,
    cadence: str,
    lookback: int,
    models: Sequence[str],
    tier: str | None = None,
) -> list[str]:
    tags: list[str] = []
    portfolio_dir = RESULTS_DIR / "portfolio"
    suffix = f"_{cadence}_{lookback}d"
    for m in models:
        pattern = f"daily_returns_{universe}_{m}*{suffix}.parquet"
        for path in sorted(portfolio_dir.glob(pattern)):
            stem = path.stem
            prefix = f"daily_returns_{universe}_"
            if not stem.startswith(prefix) or not stem.endswith(suffix):
                continue
            tag = stem[len(prefix):-len(suffix)]
            if tier and f"_{tier}" not in tag:
                continue
            if tag not in tags:
                tags.append(tag)
    preferred = [t for t in tags if f"predh{lookback}d" in t]
    return preferred or tags


def plot_equity_curves(
    universe: str,
    tier: str = "enhanced",
    models: Sequence[str] = ("ridge", "lightgbm", "xgboost"),
    cadence: str = "weekly",
    lookback: int = 5,
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    fig, ax = plt.subplots(figsize=(7.5, 3.8))

    baseline = _read_portfolio_daily(universe, None, cadence, lookback)
    if baseline is not None:
        cum = (1 + baseline["pnl"]).cumprod()
        ax.plot(baseline["date"], cum, label="ATC Baseline", color="black", linewidth=1.5, alpha=0.7)

    colors = plt.cm.tab10.colors
    model_tags = _find_model_tags(universe, cadence, lookback, models, tier=tier)
    for i, tag in enumerate(model_tags):
        df = _read_portfolio_daily(universe, tag, cadence, lookback)
        if df is None:
            continue
        cum = (1 + df["pnl"]).cumprod()
        ax.plot(df["date"], cum, label=tag.capitalize(), color=colors[(i + 1) % 10], linewidth=1.0)

    ax.axhline(y=1.0, color="gray", linestyle="--", linewidth=0.8)
    ax.set_title(f"Cumulative L/S Equity — {universe.upper()} ({tier}, {cadence} {lookback}d)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Cumulative Return")

    if baseline is None and not model_tags:
        plt.close(fig)
        raise FileNotFoundError(f"No portfolio daily returns found for {universe} ({cadence} {lookback}d)")

    ax.legend(loc="upper left")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    out = output_dir / f"equity_curves_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_ic_heatmap(
    universe: str,
    tier: str = "enhanced",
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    ic_path = RESULTS_DIR / "ic" / f"ic_summary_{universe}.parquet"
    if not ic_path.exists():
        raise FileNotFoundError(f"IC summary not found: {ic_path}")

    ic = pd.read_parquet(ic_path)
    ic_total = ic[ic["signal_type"] == "Total"]
    piv = ic_total.pivot_table(index="feature", columns="horizon", values="mean_ic", aggfunc="mean")

    fig, ax = plt.subplots(figsize=(7, max(4.5, len(piv.index) * 0.3)))
    im = ax.imshow(piv.values, aspect="auto", cmap="RdYlGn", vmin=-0.05, vmax=0.05)
    ax.set_xticks(range(len(piv.columns)))
    ax.set_xticklabels([f"h={c}d" for c in piv.columns], rotation=45, ha="right")
    ax.set_yticks(range(len(piv.index)))
    ax.set_yticklabels(piv.index, fontsize=6.5)
    ax.set_title(f"Mean Spearman IC — {universe.upper()} ({tier}, SignalType=Total)")

    for i in range(len(piv.index)):
        for j in range(len(piv.columns)):
            val = piv.iloc[i, j]
            if not np.isnan(val):
                ax.text(j, i, f"{val:.3f}", ha="center", va="center", fontsize=5.5,
                        color="white" if abs(val) > 0.035 else "black")

    fig.colorbar(im, ax=ax, shrink=0.8, label="Mean IC")
    fig.tight_layout()

    out = output_dir / f"ic_heatmap_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_quintile_spread(
    universe: str,
    tier: str = "enhanced",
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    qs_path = RESULTS_DIR / "quintile" / f"quintile_summary_{universe}.parquet"
    if not qs_path.exists():
        raise FileNotFoundError(f"Quintile summary not found: {qs_path}")

    qs = pd.read_parquet(qs_path)
    ls = qs[(qs["leg"] == "long_short") & (qs["signal_type"] == "Total")].copy()

    top_features = (
        ls.groupby("feature")["sharpe"].mean().abs().sort_values(ascending=False).head(8).index.tolist()
    )
    plot_data = ls[ls["feature"].isin(top_features)]

    horizons = sorted(plot_data["horizon"].unique())
    n_horizons = len(horizons)
    n_features = len(top_features)

    fig, ax = plt.subplots(figsize=(7.5, 3.8))
    x = np.arange(n_horizons)
    width = 0.8 / n_features

    for i, feat in enumerate(top_features):
        vals = []
        for h in horizons:
            row = plot_data[(plot_data["feature"] == feat) & (plot_data["horizon"] == h)]
            vals.append(row["sharpe"].values[0] if len(row) > 0 else np.nan)
        ax.bar(x + i * width, vals, width, label=feat[:35])

    ax.set_xticks(x + width * (n_features - 1) / 2)
    ax.set_xticklabels([f"h={h}d" for h in horizons])
    ax.set_title(f"L/S Quintile Sharpe by Feature — {universe.upper()} ({tier}, SignalType=Total)")
    ax.set_ylabel("Sharpe Ratio")
    ax.legend(loc="lower left", fontsize=6, ncol=2)
    ax.axhline(y=0, color="gray", linewidth=0.5)
    ax.grid(True, alpha=0.3, axis="y")
    fig.tight_layout()

    out = output_dir / f"quintile_spread_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_drawdown(
    universe: str,
    tier: str = "enhanced",
    models: Sequence[str] = ("ridge", "lightgbm", "xgboost"),
    cadence: str = "weekly",
    lookback: int = 5,
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    fig, ax = plt.subplots(figsize=(7.5, 3.2))

    baseline = _read_portfolio_daily(universe, None, cadence, lookback)
    if baseline is not None:
        cum = (1 + baseline["pnl"]).cumprod()
        dd = (cum - cum.cummax()) / cum.cummax()
        ax.fill_between(baseline["date"], 0, dd, label="ATC Baseline",
                        color="black", alpha=0.15, linewidth=0.5)

    colors = plt.cm.tab10.colors
    model_tags = _find_model_tags(universe, cadence, lookback, models, tier=tier)
    for i, tag in enumerate(model_tags):
        df = _read_portfolio_daily(universe, tag, cadence, lookback)
        if df is None:
            continue
        cum = (1 + df["pnl"]).cumprod()
        dd = (cum - cum.cummax()) / cum.cummax()
        ax.plot(df["date"], dd, label=tag.capitalize(), color=colors[(i + 1) % 10], linewidth=1.0)

    ax.set_title(f"Drawdown — {universe.upper()} ({tier}, {cadence} {lookback}d)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Drawdown")
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{y:.0%}"))

    if baseline is None and not model_tags:
        plt.close(fig)
        raise FileNotFoundError(f"No portfolio daily returns found for {universe} ({cadence} {lookback}d)")

    ax.legend(loc="lower left")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    out = output_dir / f"drawdown_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_rolling_sharpe(
    universe: str,
    tier: str = "enhanced",
    models: Sequence[str] = ("ridge", "lightgbm", "xgboost"),
    cadence: str = "weekly",
    lookback: int = 5,
    window: int = 252,
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    fig, ax = plt.subplots(figsize=(7.5, 3.2))

    baseline = _read_portfolio_daily(universe, None, cadence, lookback)
    if baseline is not None:
        roll = baseline["pnl"].rolling(window).mean() / baseline["pnl"].rolling(window).std() * np.sqrt(252)
        ax.plot(baseline["date"], roll, label="ATC Baseline", color="black", linewidth=1.5, alpha=0.7)

    colors = plt.cm.tab10.colors
    model_tags = _find_model_tags(universe, cadence, lookback, models, tier=tier)
    for i, tag in enumerate(model_tags):
        df = _read_portfolio_daily(universe, tag, cadence, lookback)
        if df is None:
            continue
        roll = df["pnl"].rolling(window).mean() / df["pnl"].rolling(window).std() * np.sqrt(252)
        ax.plot(df["date"], roll, label=tag.capitalize(), color=colors[(i + 1) % 10], linewidth=1.0)

    ax.axhline(y=0, color="gray", linestyle="--", linewidth=0.8)
    ax.set_title(f"Rolling {window}-Day Sharpe — {universe.upper()} ({tier}, {cadence} {lookback}d)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Sharpe Ratio")

    if baseline is None and not model_tags:
        plt.close(fig)
        raise FileNotFoundError(f"No portfolio daily returns found for {universe} ({cadence} {lookback}d)")

    ax.legend(loc="upper left")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    out = output_dir / f"rolling_sharpe_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_turnover(
    universe: str,
    tier: str = "enhanced",
    models: Sequence[str] = ("ridge", "lightgbm", "xgboost"),
    output_dir: Path | None = None,
) -> Path:
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    cadences = [("daily", 1), ("weekly", 5), ("monthly", 21)]

    records: list[dict] = []
    for cadence, lookback in cadences:
        s = _read_portfolio_summary(universe, None, cadence, lookback)
        if s:
            records.append({"cadence": cadence, "model": "ATC Baseline", "turnover": s.get("ann_turnover", 0)})
        for m in _find_model_tags(universe, cadence, lookback, models, tier=tier):
            s = _read_portfolio_summary(universe, m, cadence, lookback)
            if s:
                records.append({"cadence": cadence, "model": m, "turnover": s.get("ann_turnover", 0)})

    if not records:
        raise FileNotFoundError(f"No portfolio summaries found for {universe}")

    plot_df = pd.DataFrame(records)

    fig, ax = plt.subplots(figsize=(7, 3.5))
    cadence_labels = [c for c, _ in cadences]
    all_models = plot_df["model"].unique().tolist()
    n_models = len(all_models)
    x = np.arange(len(cadence_labels))
    width = 0.8 / n_models

    for i, m in enumerate(all_models):
        vals = []
        for cl in cadence_labels:
            row = plot_df[(plot_df["cadence"] == cl) & (plot_df["model"] == m)]
            vals.append(row["turnover"].values[0] if len(row) > 0 else 0)
        ax.bar(x + i * width, vals, width, label=m)

    ax.set_xticks(x + width * (n_models - 1) / 2)
    ax.set_xticklabels(cadence_labels)
    ax.set_title(f"Annualized Turnover — {universe.upper()} ({tier})")
    ax.set_ylabel("Annual Turnover")
    ax.legend(fontsize=6.5)
    ax.grid(True, alpha=0.3, axis="y")
    fig.tight_layout()

    out = output_dir / f"turnover_{universe}_{tier}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# Dedicated ATC baseline charts (ATCClassifierScore decile L/S, no models)
# ---------------------------------------------------------------------------


def _read_atc_baseline_daily(universe: str, horizon: int = 5) -> pd.DataFrame | None:
    """Read ATCClassifierScore decile L/S daily returns for a universe × horizon."""
    quintile_path = RESULTS_DIR / "quintile" / f"quintile_equity_curves_{universe}.parquet"
    if not quintile_path.exists():
        return None
    qdf = pd.read_parquet(quintile_path)
    key = f"{horizon}d_Total"
    subset = qdf[qdf["_key"] == key].copy()
    if subset.empty:
        return None
    subset = subset.rename(columns={"long_short": "pnl"})
    subset.index.name = "bucket_date"
    subset = subset.reset_index().rename(columns={"bucket_date": "date"})
    subset["date"] = pd.to_datetime(subset["date"])
    return subset[["date", "pnl"]].sort_values("date").dropna()


_PRETTY_UNIVERSE: dict[str, str] = {
    "sp500": "S&P 500", "sp1500": "S&P 1500", "ru3k": "Russell 3000",
}


def plot_atc_baseline_equity(
    universes: Sequence[str] = ("sp500", "sp1500", "ru3k"),
    horizons: Sequence[int] = (1, 3, 5, 10, 20),
    output_dir: Path | None = None,
) -> list[Path]:
    """Dedicated ATCClassifierScore decile L/S cumulative equity curves.

    One chart per universe showing all horizons. No model lines.
    """
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    horizon_colors = plt.cm.viridis(np.linspace(0.1, 0.9, len(horizons)))
    generated: list[Path] = []

    for univ in universes:
        fig, ax = plt.subplots(figsize=(7.5, 3.8))
        for h, color in zip(horizons, horizon_colors):
            df = _read_atc_baseline_daily(univ, h)
            if df is None:
                continue
            cum = (1 + df["pnl"]).cumprod()
            ax.plot(df["date"], cum, label=f"h={h}d", color=color, linewidth=1.2)

        ax.axhline(y=1.0, color="gray", linestyle="--", linewidth=0.8)
        label = _PRETTY_UNIVERSE.get(univ, univ.upper())
        ax.set_title(f"ATCClassifierScore Decile L/S Cumulative Return — {label}")
        ax.set_xlabel("Date")
        ax.set_ylabel("Cumulative Return")
        ax.legend(loc="upper left", title="Horizon")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        out = output_dir / f"atc_baseline_equity_{univ}.png"
        fig.savefig(out)
        plt.close(fig)
        generated.append(out)

    return generated


def plot_atc_baseline_drawdown(
    universes: Sequence[str] = ("sp500", "sp1500", "ru3k"),
    horizons: Sequence[int] = (1, 3, 5, 10, 20),
    output_dir: Path | None = None,
) -> list[Path]:
    """Dedicated ATCClassifierScore decile L/S drawdown charts.

    One chart per universe showing all horizons.
    """
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    horizon_colors = plt.cm.viridis(np.linspace(0.1, 0.9, len(horizons)))
    generated: list[Path] = []

    for univ in universes:
        fig, ax = plt.subplots(figsize=(7.5, 3.2))
        for h, color in zip(horizons, horizon_colors):
            df = _read_atc_baseline_daily(univ, h)
            if df is None:
                continue
            cum = (1 + df["pnl"]).cumprod()
            dd = (cum - cum.cummax()) / cum.cummax()
            ax.plot(df["date"], dd, label=f"h={h}d", color=color, linewidth=1.0)

        label = _PRETTY_UNIVERSE.get(univ, univ.upper())
        ax.set_title(f"ATCClassifierScore Decile L/S Drawdown — {label}")
        ax.set_xlabel("Date")
        ax.set_ylabel("Drawdown")
        ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{y:.0%}"))
        ax.legend(loc="lower left", title="Horizon")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        out = output_dir / f"atc_baseline_drawdown_{univ}.png"
        fig.savefig(out)
        plt.close(fig)
        generated.append(out)

    return generated


def plot_atc_baseline_rolling_sharpe(
    universes: Sequence[str] = ("sp500", "sp1500", "ru3k"),
    horizons: Sequence[int] = (1, 3, 5, 10, 20),
    window: int = 252,
    output_dir: Path | None = None,
) -> list[Path]:
    """Dedicated ATCClassifierScore decile L/S rolling Sharpe charts.

    One chart per universe showing all horizons.
    """
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    horizon_colors = plt.cm.viridis(np.linspace(0.1, 0.9, len(horizons)))
    generated: list[Path] = []

    for univ in universes:
        fig, ax = plt.subplots(figsize=(7.5, 3.2))
        for h, color in zip(horizons, horizon_colors):
            df = _read_atc_baseline_daily(univ, h)
            if df is None:
                continue
            roll = df["pnl"].rolling(window).mean() / df["pnl"].rolling(window).std() * np.sqrt(252)
            ax.plot(df["date"], roll, label=f"h={h}d", color=color, linewidth=1.0)

        ax.axhline(y=0, color="gray", linestyle="--", linewidth=0.8)
        label = _PRETTY_UNIVERSE.get(univ, univ.upper())
        ax.set_title(f"ATCClassifierScore Decile L/S Rolling {window}-Day Sharpe — {label}")
        ax.set_xlabel("Date")
        ax.set_ylabel("Sharpe Ratio")
        ax.legend(loc="upper left", title="Horizon")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        out = output_dir / f"atc_baseline_rolling_sharpe_{univ}.png"
        fig.savefig(out)
        plt.close(fig)
        generated.append(out)

    return generated


def plot_atc_baseline_signaltype_comparison(
    universes: Sequence[str] = ("sp500", "sp1500", "ru3k"),
    horizon: int = 5,
    signal_types: Sequence[str] = ("Total", "CEO", "CFO", "Analysts", "Executives"),
    output_dir: Path | None = None,
) -> list[Path]:
    """ATCClassifierScore decile L/S cumulative equity by SignalType.

    One chart per universe comparing SignalType slices at a fixed horizon.
    """
    import matplotlib.pyplot as plt

    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    colors = plt.cm.tab10.colors
    generated: list[Path] = []

    for univ in universes:
        quintile_path = RESULTS_DIR / "quintile" / f"quintile_equity_curves_{univ}.parquet"
        if not quintile_path.exists():
            continue
        qdf = pd.read_parquet(quintile_path)

        fig, ax = plt.subplots(figsize=(7.5, 3.8))
        for i, st in enumerate(signal_types):
            key = f"{horizon}d_{st}"
            subset = qdf[qdf["_key"] == key].copy()
            if subset.empty:
                continue
            subset.index.name = "bucket_date"
            subset = subset.reset_index().rename(columns={"bucket_date": "date"})
            subset["date"] = pd.to_datetime(subset["date"])
            subset = subset.sort_values("date").dropna(subset=["long_short"])
            cum = (1 + subset["long_short"]).cumprod()
            ax.plot(subset["date"], cum, label=st, color=colors[i % 10], linewidth=1.2)

        ax.axhline(y=1.0, color="gray", linestyle="--", linewidth=0.8)
        label = _PRETTY_UNIVERSE.get(univ, univ.upper())
        ax.set_title(f"ATCClassifierScore Decile L/S by SignalType — {label} (h={horizon}d)")
        ax.set_xlabel("Date")
        ax.set_ylabel("Cumulative Return")
        ax.legend(loc="upper left")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        out = output_dir / f"atc_baseline_signaltype_{univ}.png"
        fig.savefig(out)
        plt.close(fig)
        generated.append(out)

    return generated


def generate_all(
    universe_names: Sequence[str] = ("sp500", "sp1500", "ru3k"),
    tier: str = "enhanced",
    models: Sequence[str] = ("ridge", "lightgbm", "xgboost"),
    cadence: str = "weekly",
    lookback: int = 5,
    output_dir: Path | None = None,
) -> list[Path]:
    set_style()
    output_dir = output_dir or FIGURES_DIR
    ensure_dirs()

    generated: list[Path] = []
    chart_types: list[tuple[str, str]] = [
        ("equity_curves", f"equity_curves_{{}}_{tier}.png"),
        ("ic_heatmap", f"ic_heatmap_{{}}_{tier}.png"),
        ("quintile_spread", f"quintile_spread_{{}}_{tier}.png"),
        ("drawdown", f"drawdown_{{}}_{tier}.png"),
        ("rolling_sharpe", f"rolling_sharpe_{{}}_{tier}.png"),
        ("turnover", f"turnover_{{}}_{tier}.png"),
    ]

    for universe in universe_names:
        for chart_name, expected_fname in chart_types:
            out_path = output_dir / expected_fname.format(universe)
            try:
                if chart_name == "equity_curves":
                    out_path = plot_equity_curves(universe, tier, models, cadence, lookback, output_dir)
                elif chart_name == "ic_heatmap":
                    ic_path = RESULTS_DIR / "ic" / f"ic_summary_{universe}.parquet"
                    if not ic_path.exists():
                        print(f"  SKIP {chart_name} — no IC data for {universe}", file=sys.stderr)
                        continue
                    out_path = plot_ic_heatmap(universe, tier, output_dir)
                elif chart_name == "quintile_spread":
                    qs_path = RESULTS_DIR / "quintile" / f"quintile_summary_{universe}.parquet"
                    if not qs_path.exists():
                        print(f"  SKIP {chart_name} — no quintile data for {universe}", file=sys.stderr)
                        continue
                    out_path = plot_quintile_spread(universe, tier, output_dir)
                elif chart_name == "drawdown":
                    out_path = plot_drawdown(universe, tier, models, cadence, lookback, output_dir)
                elif chart_name == "rolling_sharpe":
                    out_path = plot_rolling_sharpe(universe, tier, models, cadence, lookback, output_dir=output_dir)
                elif chart_name == "turnover":
                    out_path = plot_turnover(universe, tier, models, output_dir)
                generated.append(out_path)
                print(f"  {out_path.name}")
            except FileNotFoundError as e:
                print(f"  SKIP {chart_name} for {universe}: {e}", file=sys.stderr)
            except Exception as e:
                print(f"  FAIL {chart_name} for {universe}: {e}", file=sys.stderr)

    # Dedicated ATC baseline charts (ATCClassifierScore decile, no models)
    print("  --- ATC Baseline charts ---")
    try:
        generated.extend(plot_atc_baseline_equity(universe_names, output_dir=output_dir))
        generated.extend(plot_atc_baseline_drawdown(universe_names, output_dir=output_dir))
        generated.extend(plot_atc_baseline_rolling_sharpe(universe_names, output_dir=output_dir))
        generated.extend(plot_atc_baseline_signaltype_comparison(universe_names, output_dir=output_dir))
    except Exception as e:
        print(f"  FAIL baseline charts: {e}", file=sys.stderr)

    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate report charts from results/")
    parser.add_argument("--tier", default="enhanced", choices=["enhanced", "stretch", "both"])
    parser.add_argument("--universes", nargs="+", default=["sp500", "sp1500", "ru3k"])
    parser.add_argument("--models", nargs="+", default=["ridge", "lightgbm", "xgboost"])
    parser.add_argument("--cadence", default="weekly")
    parser.add_argument("--lookback", type=int, default=5)
    parser.add_argument("--output-dir", type=Path, default=FIGURES_DIR)
    args = parser.parse_args()

    tiers = ["enhanced", "stretch"] if args.tier == "both" else [args.tier]

    for t in tiers:
        print(f"Charts: tier={t} universes={args.universes}")
        generated = generate_all(
            universe_names=args.universes,
            tier=t,
            models=args.models,
            cadence=args.cadence,
            lookback=args.lookback,
            output_dir=args.output_dir,
        )
        print(f"  Generated {len(generated)} charts -> {args.output_dir}")


if __name__ == "__main__":
    main()
